#!/bin/bash
urls=(
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrCe0aUI2nKOUYMlsjSLiSlXO3r8ZkyRgM8zaiH6N3QLymfC0YwGclEh2r&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9xz9Ib5L7pbBA4hKBaCDy1G_wZxTF8DGEgggfKkM7vGWcVJeI6tzXf_h1&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgbAyXaDewCAdW5MHQEM5fv1akEAYPmSkCkyB-ylcMEA9TnU4A_2p3L69s&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGjGb5eS6bu59jvIpfNe8_w_3MpiD9mC4Z8aZP1WlwZPtbU2MBKi9-_kvp&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpS3JrKXDqAZStpjLTiCsZrKKWiZChxQ9cCw&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4za0O-YOgdxqVGTu0Z-HNvfZkaFMhnJ2i9Q&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5qDqV1j_02OdZGNWhclTMwch9jxKVAI5oLw&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQC_HK3l6wg2TD4BtFai9NHX8BNdUjBZDgnAg&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSksz6nFwDYdykZP6Rly3mrLBErXnTvXac_LQ&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuSmApY4n78Ltm-v9Jb-go5F-o9sijFWu7Dw&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQc48Vb049-WEgQ0VzqbjvNjC4l0BTZfZa_1Q&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7XoZBLqmTIW4cpvP6oYk44AWKaZ6YIJnxJQ&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhwVQ1nc9xGKsnUpl4-79dSO3xokFS3iJpuw&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNzNssAivsb8O1FLj9ZhPzeTMo_PM8lHnmtA&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRF_AnGQgiXIaoU9qoplfVHWhKOdkWz7Zm4Hw&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvfFI_EQ96CSxjuCGEXBPqBtZDgtJepZqukA&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHXJRemWjjYM5GdAivnCIXUnEr7UrS43JwPQ&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAr-dtC18CZq1lFnwgACg-NyPJhZYnvCEbcw&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSv67gIUZ9_z_xX5HWp8v-OxBiZmSDr73d1eQ&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOCtfPJVGFOBh7nAwtP8NEk4-ZuROZUDtVfg&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQQ7S9DNzQf7kHME0zozhwisM65FzvFJ62cWg&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTR79K2Uwaj8ZE0267tKq15uvlej40E0IAEgg&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdybRVUXBOmBnSUZUXkeHoeRmr1KQFGbzx5g&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT_4d0zWsgfE_oHAw2ZsVza7r8WrBYBaERhw&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvEWOTNoJOU5PUUgm8-KDCr6YdsdLWVyCCIw&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsb-Xtz59SfGGeki74qME_OIL89zr-hwGsgQ&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1_cRpT778MYYk_uqm3COp_0A21Ry8HXuTSA&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRddMmcAxh7uItVnNoNrrwyKzevicK9zKr1zA&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAoxOmyAIHJCM6PrlWraxSiskQupZjhoWRqQ&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1Yb8uelSLWkoYQc07R0DgK_FlctTMkZGF8A&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUUQqWsJTw5YXmFQlOtIwzQvm1k7pznZaclA&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCzCWQkHLmzw0baajZBtVLJRpNFYbaLayDIQ&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVvYRRAr7wIXlp6650RyVmLsi__Dy-XB56kg&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT1C0fOkn8lEMn0qORzW8F20qXru_FFQ-SbGA&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqQDWCiU-7BnPrYXf7N-4ib_PN87AAxaGR6g&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDiofPBh8_4qjX4SAmP8RZnQT69wQr3eLz_w&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAi-ACACZ11nkdipx2M4LB7xsC7xEG3s3LXA&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSGa1zb8WzOXe5R_BWtruWNrdlVanz0OvuusA&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRu6byMhURq9klZjjq6ta_vqMSveCcBm4-VxA&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsM-P-SbJJwov3koOz1KbFRk-pckHgH43bLg&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZyR5FWYiDxfUynRQ6WcGg-Pr-SRHhd5Gs8g&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJgsD-xi13MO_ucAkrKaHe5mrX51IWYz8QVg&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTL1iNyAVwAG8pyUuhjC81ganAx3YzqeR-iig&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBTih1qAdQGNX-Jr1wqCuCUoleZRYwUXX6wQ&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTo7jt_guLpvWE_j3hfM5RgQ4jY8w6J0fNmww&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIJEamQLJvafdzGT9PgEJ1EfyqebEVRN31CQ&s"
"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmSJrGIwfdKYJkZnGjvIrbbb5010loYbL5XQ&s"
"https://render.fineartamerica.com/images/images-profile-flow/400/images/artworkimages/mediumlarge/3/my-dream-place-tithi-luadthong.jpg"
"https://render.fineartamerica.com/images/images-profile-flow/400/images/artworkimages/mediumlarge/1/journey-to-outer-space-tithi-luadthong.jpg"
"https://render.fineartamerica.com/images/images-profile-flow/400/images/artworkimages/mediumlarge/1/red-moon-night-tithi-luadthong.jpg"
)

count=1
for url in "${urls[@]}"; do
  filename=$(printf "tithi_%02d.jpg" $count)
  curl -s -o "$filename" "$url"
  echo "Downloaded: $filename"
  count=$((count + 1))
  if [ $count -gt 50 ]; then break; fi
done
echo "Done! Downloaded $((count-1)) images"
